### ISSUE TITLE
admin media gone

### ISSUE THREAD

**Issue by themotu** [donnex/django-docker-coookiecutter#1]
Maybe I'm missing a step but why is the admin media missing? Also why are you not linking in "web" to nginx and not binding it locally? I'm just curious your methodology and reasoning, would you mind going over why you did each step and how you develop? (if not that's fine obviously)

**Comment by donnex** [comment]
Hi, I would love to explain it in detail but I'm a bit short on time at the moment.

To be honest I have only used this setup on a personal project rewrite. And that's not very far along because of lack of time. The setup worked perfectly for me but I'm sure there is a lot of stuff one could change and make better / more efficient. It is a bit of fiddling around to get into it but when I got ut running it was very nice, for me at least :)

The setup is basically my personal taste for how I like to setup and develop Django web project merged with a Docker setup to reduce dependencies and get everything isolated and structured.

As I said I haven't really had the time to reflect on the setup or to even use it extensively. I just got the template and project structure done and then other stuff got in between :P

I don't know if I understand the question correctly but I am linking web to nginx. The reason is that I want my web container (the one running Python, Gunicorn and Django) as a stand alone container. That way I can move this container and run only run this part. In this setup I then run a Nginx container to mimic a production setup where I would use Nginx in front. What I actually do is to also run a stand alone Docker container outside the Fig/Docker Compose setup. This container binds to my Docker hosts port 80 and then act as a proxy to my different dev projects.

I'm running a Mac so I add my dev host to my /etc/hosts, example.com.dev for example. I then add 
`VIRTUAL_HOST: example.com.dev`
to my fig.yml / docker-compose.yml to the Nginx section.
I then run run https://github.com/jwilder/nginx-proxy with docker run outside fig. This container binds to port 80 and sees that example.com.dev should be proxied to my projects Nginx.
`docker nginx-proxy -> project nginx container -> web container running Gunicorn`

Using this additional container lets me run all project on port 80, I don't have to change the port and run all projects on different ports and I can have multiple projects running att the same time. This may be a bit complicated and overdoing it but it works for me. I would love to get feedback if there is smarter or better ways to do it.

What I haven't had time to figure out or test is how to take this into production. I played around a bit with setting up a private Docker repo and upload the web image (pre built with code etc) and then check it out and run it on the production server. But I still don't really know how to handle the static + media (user uploaded) files etc. I would love some feedback, pull requests etc. if you know any ways to improve it. This is really my first try with Django + Docker.

You asked about the admin media. What I actually does is to run manage.py collectstatic. This collects all static files and put them in the static folder. This folder is then served as a static folder in the Nginx container and the admin media works when this is done.
`web/stepup/PROJECT_NAME/static`
What I have to do is to chmod 777 the static folder to make it writable from Docker. I guess it would be possible to make this setup a bit cleaner to.

**Comment by themotu** [comment]
I use nginx proxy as well on my boxes. 

I'm interested in collaborating into making this a turnkey from dev to prod setup if you'd like. This kind of setup will become pretty standard now that fig(compose) is being baked directly into docker. I spin up a lot of small django sites and would be interested in getting something like this working down to a T. If you're not interested or are too time restricted I totally understand. 

One of the things that is very interesting to me is rancher from rancher.com and I'm not sure how they're going to implement compose yet but I'm pretty sure compose is going to be baked into docker 1.6. I'm trying to confirm that now in irc. (this may be relevent for future)

**Comment by themotu** [comment]
Okay here is current fix for admin media issue. I haven't bothered to get into the actual code to submit a patch yet.

if I add this to the web volumes
./web/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/static:/static

then do the following:

docker-enter (web_container_ID)
chmod 777 static
fig run --rm web ./manage.py collectstatic

I can get static working haha

**Comment by donnex** [comment]
Hi, thanks for the feedback :)

I would love to collaborate on creating the perfect Django Docker setup but I just don't have the time at the moment.

If you do any further work on this setup or another Django setup please let me know.

**Comment by themotu** [comment]
Will do, I'll probably just fork this and modify it to work how I envision it and make it prod ready. I'll also be configuring self generated ssl and an admin sub domain with https redirect.

Sent from my iPhone

On Apr 1, 2015, at 11:35 AM, Daniel Johansson <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, thanks for the feedback :)

I would love to collaborate on creating the perfect Django Docker setup but I just don't have the time at the moment.

If you do any further work on this setup or another Django setup please let me know.

**Comment by donnex** [comment]
I'm closing this ticket as it's no longer needed.

Good luck with the continuation of the project, whatever it ends up being :)
